/*
* This is action-type of viewing approved appointment in case success or failure.
*/
export const DOCOTR_FETCH_APPROVED_APPOINTMENT_SUCCESS = 'DOCOTR_FETCH_APPROVED_APPOINTMENT_SUCCESS';
export const DOCOTR_FETCH_APPROVED_APPOINTMENT_FAILURE = 'DOCOTR_FETCH_APPROVED_APPOINTMENT_FAILURE';
