/*
* This is action-type of viewing pending appointment in case success or failure.
*/
export const DOCOTR_FETCH_REJECTED_APPOINTMENT_SUCCESS = 'DOCOTR_FETCH_REJECTED_APPOINTMENT_SUCCESS';
export const DOCOTR_FETCH_REJECTED_APPOINTMENT_FAILURE = 'DOCOTR_FETCH_REJECTED_APPOINTMENT_FAILURE';
